export enum TimeOffRequestStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FAILED_HCM_SUBMISSION = 'FAILED_HCM_SUBMISSION',
  CANCELLED = 'CANCELLED',
}
