export enum MockHcmFailureMode {
  NONE = 'NONE',
  TIMEOUT = 'TIMEOUT',
  SERVER_ERROR = 'SERVER_ERROR',
  MALFORMED_RESPONSE = 'MALFORMED_RESPONSE',
  IGNORE_INSUFFICIENT_BALANCE = 'IGNORE_INSUFFICIENT_BALANCE',
}
