export const ErrorCodes = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_REQUEST_DAYS: 'INVALID_REQUEST_DAYS',
  INVALID_DIMENSION: 'INVALID_DIMENSION',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_NOT_APPROVABLE: 'REQUEST_NOT_APPROVABLE',
  HCM_UNAVAILABLE: 'HCM_UNAVAILABLE',
  HCM_INVALID_RESPONSE: 'HCM_INVALID_RESPONSE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
